### PR TITLE
Add Import/Export Keywords

### PR DESCRIPTION
**Pull request by audinue**
This pull request adds `import`, `as`, `from` and `export` to `keyword.other.coffee` in `CoffeeScript.tmLanguage`.

### CODE REVIEW

**Comment by GeoffreyBooth** [comment]
This feels like the wrong place for this. I would think these keywords should be defined near where we define things like `for` and `throw`.

**Comment by nwbauer** [comment]
FWIW, I also wanted this feature.  Since this seems like the PR will no go forward, so I thought I would post my workaround here:

1. With a coffeescript edited document open, go to Tools > Developer > New Syntax from Coffeescript.tmLanguage...

screen shot 2018-02-04 at 4 56 10 pm

2. When the document opens, change the name: to something different, e.g.  `name: CoffeeScript Custom`

3. In contexts: main: add the lines

```
contexts:
  main:
   ...
    - match: '\b(import|as|from|export)\b'
      scope: keyword.operator.coffee
```
4. Save the file in the default directory, and now you can use your new Coffeescript Custom syntax!

**Comment by auvipy** [comment]
https://github.com/aponxi/sublime-better-coffeescript/issues/243 ?

**Comment by GeoffreyBooth** [comment]
I would be happy to merge in a PR that adds support for the missing keywords, but they should be defined in the proper place in the file. They shouldn’t be overloading `debugger`.

**Pull request closed without merging**
